---
openapi: 3.0.0

info:
  title: Loyalty Challenges
  description: |
    APIs for the **Loyalty Challenges** feature (private beta). Use this service to manage and query loyalty challenge state.

    <br/><br/>**Availability:** This API is available in private beta. Contact Adobe for access.
    <br/><br/>**Related documentation:** See [Loyalty challenges](https://experienceleague.adobe.com/docs/journey-optimizer/using/loyalty-challenges/get-started.html) in Journey Optimizer documentation.
    <br/><br/>**Required headers:** All calls require the headers Authorization, x-gw-ims-org-id, and x-api-key. For more information, see the [authentication tutorial](https://developer.adobe.com/journey-optimizer-apis/references/authentication/).
  version: "1.0.0"
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

security:
  - BearerAuth: []

servers:
  - url: https://platform-stage.adobe.io/ajo
    description: Stage Environment
  - url: https://platform.adobe.io/ajo
    description: Production Environment

paths:
  # Replace the paths below with the full specification from the internal API spec.
  # Source: Loyalty Challenge State Service (private beta)
  /loyalty/challenge-state:
    parameters:
      - $ref: '#/components/parameters/x-api-key'
      - $ref: '#/components/parameters/x-request-id'
      - $ref: '#/components/parameters/x-gw-ims-org-id'
      - $ref: '#/components/parameters/x-sandbox-name'
    get:
      summary: Get loyalty challenge state (placeholder)
      tags:
        - Loyalty Challenges
      operationId: getLoyaltyChallengeState
      description: Placeholder. Replace this file with the full OpenAPI spec from the Loyalty Challenge State Service.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: The authentication token to access the service.

  parameters:
    x-api-key:
      name: x-api-key
      description: The API key belonging to the calling client.
      required: true
      in: header
      schema:
        type: string
    x-request-id:
      name: x-request-id
      description: A unique id for the request (optional).
      required: false
      in: header
      schema:
        type: string
    x-gw-ims-org-id:
      name: x-gw-ims-org-id
      description: The IMS org id for which the action is being taken.
      required: true
      in: header
      schema:
        type: string
    x-sandbox-name:
      name: x-sandbox-name
      description: The platform Sandbox name.
      required: true
      in: header
      schema:
        type: string

  schemas:
    errorResponse:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        status:
          type: integer
