---
openapi: 3.0.0

info:
  description: Interactive Message Execution API
  version: "1.0.0 - Beta Version"
  title: Interactive Message Execution API


externalDocs:
  description: API Documentation
  url: https://wiki.corp.adobe.com/display/CJM/Headless+Messaging+API+Specifications

security:
  - imsUserToken: []

servers:
  - url: https://cjm-dev.adobe.io/imp/message
    description: dev env
  - url: https://cjm-stage.adobe.io/imp/message
    description: stage env
  - url: https://cjm.adobe.io/imp/message
    description: prod env

paths:
  /im/executions/unitary:
    parameters:
      - $ref: '#/components/parameters/x-api-key'
      - $ref: '#/components/parameters/x-request-id'
      - $ref: '#/components/parameters/x-gw-ims-org-id'
      - $ref: '#/components/parameters/x-sandbox-name'

    post:
      summary: "Trigger an unitary message execution."
      tags:
        - execution
      operationId: postIMUnitaryMessageExecution
      security:
        - imsUserToken: []
      description: ""
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/imExecutionRequestUnitary'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/imExecutionResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  securitySchemes:
    imsUserToken: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  parameters:
    x-api-key:
      name: x-api-key
      description: The API key belonging to the calling client.
      required: true
      in: header
      schema:
        type: string
    x-request-id:
      name: x-request-id
      description: A unique id generated by Adobe.io.
      required: false
      in: header
      schema:
        type: string
    x-gw-ims-org-id:
      name: x-gw-ims-org-id
      description: The ims org id for which the action is being taken.
      required: true
      in: header
      schema:
        type: string
    x-sandbox-name:
      name: x-sandbox-name
      description: >-
        Provides the platform Sandbox Name
      required: true
      in: header
      schema:
        type: string

  schemas:
    imExecutionRequestUnitary:
      description: "the IM Execution Request Unitary"
      type: object
      required:
        - requestId
        - recipients
      properties:
        requestId:
          type: string
          description: "the Unique Request Identifier"
          example: "request-12345"
        campaignId:
          type: string
          description: "the Campaign Identifier"
          example: "campaign-12345"
        recipients:
          $ref: '#/components/schemas/recipients'
        contextData:
          $ref: '#/components/schemas/contextData'
        content:
          $ref: '#/components/schemas/content'


    imExecutionResponse:
      description: "the execution response"
      type: object
      properties:
        executionId:
          description: "the execution ID"
          type: string
          example: "UMA-00859153"
        requestId:
          description: "the request ID"
          type: string
          example: "REQ-80940549"
        createdAt:
          type: string
          format: date-time
          description: "the message execution creation time"
          example: "2016-08-29T09:12:33.001Z"
        createdBy:
          description: "the message execution creation user"
          type: string
          example: "5d1281e6d935456i4273@AdobeId"
        # modification details can be removed after addressing Auditable dependency
        modifiedAt:
          type: string
          format: date-time
          description: "the message execution modification time"
          example: '2016-08-29T09:12:33.001Z'
        modifiedBy:
          description: "the message execution modification user"
          type: string
          example: '4c0190e5d702748f0931@AdobeId'

    errorResponse:
      description: "the error response"
      type: object
      properties:
        type:
          type: string
          description: "the error type"
          example: "https://ns.adobe.com/aep/errors/MSG-000052-400"
        title:
          type: string
          description: "the error title"
          example: "An error has occurred"
        status:
          description: "the error status"
          type: integer
          example: 400
        report:
          description: "the error report"
          type: object
          properties:
            additionalContext:
              additionalProperties:
                type: string
          required:
            - additionalContext
          example:
            "additionalContext": {
              "requestId":"04e7a2a5-f6db-4d15-a1ba-edda77bdb66f",
              "campaignId": "campaign-1234567"
            }

    recipients:
      type: array
      description: "the list of recipients"
      items:
        oneOf:
          - $ref: "#/components/schemas/AEPRecipient"
          - $ref: "#/components/schemas/externalRecipient"
        discriminator:
          propertyName: type
          mapping:
            aep: "#/components/schemas/AEPRecipient"
            external: "#/components/schemas/externalRecipient"
      minItems: 1
      maxItems: 20

    AEPRecipient:
      type: object
      description: "the AEP Recipient Information"
      required:
        - type
        - userId
        - namespace
      properties:
        type:
          type: string
          description: "recipient type: aep"
          example: "aep"
        userId:
          type: string
          description: "the AEP Profile identifier"
          example: "AEP-ProfileID-12345"
        namespace:
          type: string
          description: "the AEP Profile namespace"
          example: "ecid"
        channelData:
          $ref: "#/components/schemas/recipientChannelData"
        contextData:
          $ref: "#/components/schemas/contextData"

    externalRecipient:
      type: object
      description: "the External Recipient Information"
      required:
        - type
        - userId
        - channelData
      properties:
        type:
          type: string
          description: "recipient type: external"
          example: "external"
        userId:
          type: string
          description: "the external user identifier. Can be email id or any other unique identifier"
          example: "customer123@example.com"
        channelData:
          $ref: "#/components/schemas/recipientChannelData"
        contextData:
          $ref: "#/components/schemas/contextData"

    recipientChannelData:
      type: object
      description: "the Channel Data for recipient"
      properties:
        emailAddress:
          type: string
          description: "the email address for emailing which also doubles up as the external userId"
          example: "customer123@example.com"
        mobilePhoneNumber:
          type: string
          description: "the mobile phone number for sms"
          example: "+1 999-999-9999"

    contextData:
      type: object
      description: "the context data used for dynamic variable substitution in message content"
      additionalProperties:
        oneOf:
          - type: string
          - type: object
      example:
          {
             "customer": {"loyalty": "Premium", "region": "AMER"},
             "product": {"name": "Gaming Laptop", "category": "Computers"},
             "name": {"firstName": "Jane", "lastName": "Doe"}
          }
          # Multiple examples support is not available in the currently used OpenAPI version
          # So showing additional examples as comments
          # Example 2: Simple string properties
          # {
          #   "productName": "LED TV",
          #   "productCategory": "Electronics"
          # }

    content:
      type: object
      description: 'the channel based message contents'
      properties:
        email:
          $ref: '#/components/schemas/emailContent'
        sms:
          $ref: '#/components/schemas/smsContent'

    emailContent:
      type: object
      description: "the email content"
      required:
        - presetId
        - subject
        - body
      properties:
        presetId:
          type: string
          description: "the email preset identifier"
          example: "preset-1234"
        messageType:
          type: string
          description: "the message type identifier - 'marketing' or 'transactional'"
          default: "transactional"
          example: "transactional"
        subject:
          type: string
          description: "the email subject which can have variables in this format: {{context.variable}}"
          example: "Welcome to AJO Interactive Messaging {{context.person.name.lastName}}"
        body:
          type: string
          description: "the email body which can have variables in this format: {{context.variable}}"
          example: "Hi {{context.person.name.lastName}}, Greetings..."

    smsContent:
      type: object
      description: "the SMS content"
      required:
        - presetId
        - body
      properties:
        presetId:
          type: string
          description: "the SMS preset identifier"
          example: "preset-3456"
        messageType:
          type: string
          description: "the message type identifier - 'marketing' or 'transactional'"
          default: "transactional"
          example: "transactional"
        body:
          type: string
          description: "the SMS body which can have variables in this format: {{context.variable}}"
          example: "Hi {{context.person.name.lastName}}, Greetings..."